-- Generated by scripts/backfill-rdl-titles.ts. Review, then run once in Supabase SQL Editor.
begin;

create temporary table rdl_title_backfill (
  material_id text primary key,
  old_title text not null,
  previous_title text not null,
  new_title text not null,
  action text not null check (action in ('KEEP_ORIGINAL', 'GENERATE_SHORT_TITLE')),
  english_word_count integer not null check (english_word_count between 1 and 5)
) on commit drop;

insert into rdl_title_backfill values
  ('RDL-001', 'University Robotics Club Workshop', 'University Robotics Club Workshop', 'University Robotics Club Workshop', 'KEEP_ORIGINAL', 4),
  ('RDL-002', 'Dorm Printer Setup Instructions', 'Dorm Printer Setup Instructions', 'Dorm Printer Setup Instructions', 'KEEP_ORIGINAL', 4),
  ('RDL-003', 'Elena Rowe (4:44 P.M.)', 'Mini Fridge Repair Chat', 'Mini Fridge Repair Chat', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-004', 'IN TUNE WITH WELL-BEING: A Full-Spectrum Wellness Journey', 'Full-Spectrum Wellness Journey', 'Full-Spectrum Wellness Journey', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-005', 'Discover Larkhaven, where lecture halls open to cobblestone courtyards abuzz with debate and steaming coffee.', 'Life at Larkhaven', 'Life At Larkhaven', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-006', 'UNIVERSITY HEALTH AND WELLNESS CONFERENCE', 'UNIVERSITY HEALTH AND WELLNESS CONFERENCE', 'University Health And Wellness Conference', 'KEEP_ORIGINAL', 5),
  ('RDL-007', 'Fall Midterm Schedule', 'Fall Midterm Schedule', 'Fall Midterm Schedule', 'KEEP_ORIGINAL', 3),
  ('RDL-008', 'Greetings from an Eliot fan', 'Greetings from an Eliot fan', 'Greetings From An Eliot Fan', 'KEEP_ORIGINAL', 5),
  ('RDL-009', 'Mystery is a Must-See', 'Mystery is a Must-See', 'Mystery Is A Must-See', 'KEEP_ORIGINAL', 4),
  ('RDL-010', 'ON MARCH 18, FILM STUDIES MAJORS PRESENTED THEIR WORK AT ADLER AUDITORIUM.', 'Student Film Showcase', 'Student Film Showcase', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-011', 'Dormitory Quiet Hours', 'Dormitory Quiet Hours', 'Dormitory Quiet Hours', 'KEEP_ORIGINAL', 3),
  ('RDL-012', 'Stay Healthy During Cold And Flu Season', 'Cold and Flu Prevention', 'Cold And Flu Prevention', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-013', '★ ★ ★  Tasty Bites  ★ ★ ★', 'Tasty Bites', 'Tasty Bites', 'KEEP_ORIGINAL', 2),
  ('RDL-014', 'Revitalizing Campus Life at Ridgeview University', 'Revitalizing Ridgeview Campus Life', 'Revitalizing Ridgeview Campus Life', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-015', 'GoodBooks shipment', 'GoodBooks shipment', 'Goodbooks Shipment', 'KEEP_ORIGINAL', 2),
  ('RDL-016', 'Literature 201: Introduction to World Literature', 'Literature 201: Introduction to World Literature', 'Literature 201: Introduction To World Literature', 'KEEP_ORIGINAL', 5),
  ('RDL-017', 'Sandeep Patel (10:00 A.M.)', 'Concert Planning Chat', 'Concert Planning Chat', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-018', 'Internship fair follow-up', 'Internship fair follow-up', 'Internship Fair Follow-Up', 'KEEP_ORIGINAL', 3),
  ('RDL-019', 'ENGL 102: Introduction to Literature II', 'ENGL 102: Introduction to Literature II', 'Engl 102: Introduction To Literature Ii', 'KEEP_ORIGINAL', 5),
  ('RDL-020', 'Instructions for Resetting Your Dorm Room Router', 'Dorm Router Reset Instructions', 'Dorm Router Reset Instructions', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-021', 'Join us on Saturday, June 21, from 10:00 A.M. to 6:00 P.M. for the grand opening of Radiant Beauty Salon! Enjoy complimentary refreshments, live music, and exclusive offers:', 'Radiant Beauty Salon Opening', 'Radiant Beauty Salon Opening', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-022', 'CAMPUS RESEARCHERS “CRACK” THE CONCRETE CODE', 'Self-Healing Concrete Breakthrough', 'Self-Healing Concrete Breakthrough', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-023', 'Organic Chemistry I', 'Organic Chemistry I', 'Organic Chemistry I', 'KEEP_ORIGINAL', 3),
  ('RDL-024', 'Dear Club Coordinator,', 'Request to join Debate Club', 'Request To Join Debate Club', 'KEEP_ORIGINAL', 5),
  ('RDL-025', 'Welcome to the Williamsville College Gardening Club!', 'Williamsville Gardening Club', 'Williamsville Gardening Club', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-026', 'Award Winner Returns to Alma Mater By Kevin Martin', 'Actor Returns to Campus', 'Actor Returns To Campus', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-027', 'Student Center Closure', 'Student Center Closure', 'Student Center Closure', 'KEEP_ORIGINAL', 3),
  ('RDL-028', 'DORM STARTUP GOES VIRAL', 'DORM STARTUP GOES VIRAL', 'Dorm Startup Goes Viral', 'KEEP_ORIGINAL', 4),
  ('RDL-029', 'Booking inquiry', 'Booking inquiry', 'Booking Inquiry', 'KEEP_ORIGINAL', 2),
  ('RDL-030', 'Reviews and Opinions @CampusDaily Review of The Kansas Kerfuffle', 'Review of The Kansas Kerfuffle', 'Review Of The Kansas Kerfuffle', 'KEEP_ORIGINAL', 5),
  ('RDL-031', 'My thesis proposal', 'My thesis proposal', 'My Thesis Proposal', 'KEEP_ORIGINAL', 3),
  ('RDL-032', 'Angela Kim (5:00 P.M.)', 'Student Hiking Plans', 'Student Hiking Plans', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-033', 'Membership Application Form First Name: ____________________', 'Membership Application Form', 'Membership Application Form', 'KEEP_ORIGINAL', 3),
  ('RDL-034', 'The University Photography Club', 'The University Photography Club', 'The University Photography Club', 'KEEP_ORIGINAL', 4),
  ('RDL-035', 'BIOL 101 Introduction to Biology', 'BIOL 101 Introduction to Biology', 'Biol 101 Introduction To Biology', 'KEEP_ORIGINAL', 4),
  ('RDL-036', 'Welcome to Movie Mania', 'Welcome to Movie Mania', 'Welcome To Movie Mania', 'KEEP_ORIGINAL', 4),
  ('RDL-037', 'David White', 'Flex and Flow Opening', 'Flex And Flow Opening', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-038', 'English 202: The Sonnet', 'English 202: The Sonnet', 'English 202: The Sonnet', 'KEEP_ORIGINAL', 3),
  ('RDL-039', 'Solar panels for university library', 'Solar panels for university library', 'Solar Panels For University Library', 'KEEP_ORIGINAL', 5),
  ('RDL-040', 'SIGN LANGUAGE INTERPRETER NEEDED', 'SIGN LANGUAGE INTERPRETER NEEDED', 'Sign Language Interpreter Needed', 'KEEP_ORIGINAL', 4),
  ('RDL-041', 'Frankson Library Renovation and Temporary Relocation', 'Frankson Library Relocation', 'Frankson Library Relocation', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-042', 'Ella Bottled Water (1 Case)', 'Ella Bottled Water (1 Case)', 'Ella Bottled Water (1 Case)', 'KEEP_ORIGINAL', 4),
  ('RDL-043', 'This course explores classical mechanics, thermodynamics, and electromagnetism through lectures, labs, and problem-solving sessions.', 'Introductory Physics Course', 'Introductory Physics Course', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-044', 'Downtown School of Data Skills', 'Downtown School of Data Skills', 'Downtown School Of Data Skills', 'KEEP_ORIGINAL', 5),
  ('RDL-045', 'Study Abroad Expo - Session Schedule', 'Study Abroad Expo - Session Schedule', 'Study Abroad Expo - Session Schedule', 'KEEP_ORIGINAL', 5),
  ('RDL-046', '☆ ☆ ☆  MISHTI  ☆ ☆ ☆ Exciting Indian Cuisine Near Campus', 'Mishti Indian Cuisine', 'Mishti Indian Cuisine', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-047', 'Dental appointment', 'Dental appointment', 'Dental Appointment', 'KEEP_ORIGINAL', 2),
  ('RDL-048', 'Attention Residents!', 'Attention Residents!', 'Attention Residents!', 'KEEP_ORIGINAL', 2),
  ('RDL-049', 'Serve & Shine: Volunteer Opportunities Expo', 'Serve & Shine: Volunteer Opportunities Expo', 'Serve & Shine: Volunteer Opportunities Expo', 'KEEP_ORIGINAL', 5),
  ('RDL-050', 'Welcome, Study-Abroad Students!', 'Welcome, Study-Abroad Students!', 'Welcome, Study-Abroad Students!', 'KEEP_ORIGINAL', 3),
  ('RDL-051', 'North Bay', 'College Craft-A-Thon', 'College Craft-A-Thon', 'GENERATE_SHORT_TITLE', 2),
  ('RDL-052', 'Time Capsule Unearthed During Dorm Renovation', 'Dorm Renovation Time Capsule', 'Dorm Renovation Time Capsule', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-053', 'Annual dormitory room maintenance will occur from', 'Dorm Room Maintenance', 'Dorm Room Maintenance', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-054', 'Student Housing Dilemma: A Shortage of Affordable Options', 'Affordable Student Housing Shortage', 'Affordable Student Housing Shortage', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-055', 'Library News University Library Update', 'University Library Update', 'University Library Update', 'KEEP_ORIGINAL', 3),
  ('RDL-056', 'Study Smarter: Academic Success Workshop', 'Study Smarter: Academic Success Workshop', 'Study Smarter: Academic Success Workshop', 'KEEP_ORIGINAL', 5),
  ('RDL-057', 'Mental Well-Being Workshops', 'Mental Well-Being Workshops', 'Mental Well-Being Workshops', 'KEEP_ORIGINAL', 3),
  ('RDL-058', 'CampusConnect — We make campus commuting simple!', 'CampusConnect', 'Campusconnect', 'KEEP_ORIGINAL', 1),
  ('RDL-059', 'POLS 201 Comparative Political Thought', 'POLS 201 Comparative Political Thought', 'Pols 201 Comparative Political Thought', 'KEEP_ORIGINAL', 4),
  ('RDL-060', 'Momentum Meet-up: Networking Mixer for Students', 'Student Networking Mixer', 'Student Networking Mixer', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-061', 'Library Hours and guidelines', 'Library Hours and Guidelines', 'Library Hours And Guidelines', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-062', 'Japan Study Abroad Program', 'YOUR GLOBAL CLASSROOM AWAITS!', 'Your Global Classroom Awaits!', 'KEEP_ORIGINAL', 4),
  ('RDL-063', 'Sidewalk Repair Project', 'Sidewalk Repair Project', 'Sidewalk Repair Project', 'KEEP_ORIGINAL', 3),
  ('RDL-064', 'Colin / Priya / Mateo remote-learning assignment messages', 'Remote Learning Assignment Chat', 'Remote Learning Assignment Chat', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-065', 'Discovering Human Cultures by Dr. R. J. Hancock', 'Global Cultures Documentary', 'Global Cultures Documentary', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-066', 'Summit View University Arts Week flash mob', 'Arts Week Flash Mob', 'Arts Week Flash Mob', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-067', 'Extended Library Hours for Final Exams', 'Finals Week Library Hours', 'Finals Week Library Hours', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-068', 'Supporting information needed', 'Supporting information needed', 'Supporting Information Needed', 'KEEP_ORIGINAL', 3),
  ('RDL-069', 'University STEM Peer Support Group', 'STEM Peer Support Group', 'Stem Peer Support Group', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-070', 'Gym World membership email', 'Gym membership', 'Gym Membership', 'KEEP_ORIGINAL', 2),
  ('RDL-071', 'ENGL 101 Introduction to Literature', 'ENGL 101: Introduction to Literature', 'Engl 101: Introduction To Literature', 'KEEP_ORIGINAL', 4),
  ('RDL-072', 'Urgent: Campus Transport and Traffic Advisory', 'Campus Traffic Advisory', 'Campus Traffic Advisory', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-073', 'Housing renewal application', 'Housing renewal application', 'Housing Renewal Application', 'KEEP_ORIGINAL', 3),
  ('RDL-074', 'Bella Italia campus dining notice', 'Bella Italia Dining Notice', 'Bella Italia Dining Notice', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-075', 'MATH 101 Calculus I', 'MATH 101 Calculus I', 'Math 101 Calculus I', 'KEEP_ORIGINAL', 3),
  ('RDL-076', 'Discover Estonia''s Timeless Charm', 'Discover Estonia''s Timeless Charm', 'Discover Estonia''s Timeless Charm', 'KEEP_ORIGINAL', 4),
  ('RDL-077', 'Brison College Poetry Magazine', 'Poetry Magazine Submissions', 'Poetry Magazine Submissions', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-078', 'Bridgeford University Music & Culture Night', 'BRIDGEFORD UNIVERSITY MUSIC & CULTURE NIGHT', 'Bridgeford University Music & Culture Night', 'KEEP_ORIGINAL', 5),
  ('RDL-079', 'University nuclear research reactor article', 'University Research Reactor', 'University Research Reactor', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-080', 'Campus Volunteer Day', 'CAMPUS VOLUNTEER DAY', 'Campus Volunteer Day', 'KEEP_ORIGINAL', 3),
  ('RDL-081', 'Blackout Brings Creativity to Finals Week', 'Finals Week Blackout', 'Finals Week Blackout', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-082', 'LIT 304 Shakespeare''s Kings', 'LIT304 Shakespeare''s Kings', 'Lit304 Shakespeare''s Kings', 'KEEP_ORIGINAL', 3),
  ('RDL-083', 'Student council meeting text-message chain', 'Student Council Meeting Chat', 'Student Council Meeting Chat', 'GENERATE_SHORT_TITLE', 4),
  ('RDL-084', 'CULN 310 Advanced Techniques: Sous Vide', 'CULN 310 Advanced Techniques: Sous Vide', 'Culn 310 Advanced Techniques: Sous Vide', 'KEEP_ORIGINAL', 5),
  ('RDL-085', 'Kintsugi', 'Kintsugi and Wabi-Sabi', 'Kintsugi And Wabi-Sabi', 'GENERATE_SHORT_TITLE', 3),
  ('RDL-086', 'The Rise of Sustainable Living in University Housing', 'Sustainable Campus Housing', 'Sustainable Campus Housing', 'GENERATE_SHORT_TITLE', 3);

do $$
begin
  if (select count(*) from rdl_title_backfill) <> 86 then
    raise exception 'RDL title backfill must contain exactly 86 materials';
  end if;
  if exists (
    select 1 from rdl_title_backfill b
    left join reading_materials m on m.material_id = b.material_id
    where m.material_id is null or m.title not in (b.old_title, b.previous_title, b.new_title)
  ) then
    raise exception 'RDL title preflight failed: missing material or unexpected current title';
  end if;
end $$;

update reading_materials m
set title = b.new_title
from rdl_title_backfill b
where m.material_id = b.material_id
  and m.title is distinct from b.new_title;

update reading_logical_items i
set title = mapped.new_title
from (
  select distinct q.logical_item_id, b.new_title
  from reading_questions q
  join rdl_title_backfill b on b.material_id = q.material_id
) mapped
where i.logical_item_id = mapped.logical_item_id
  and i.module = 'rdl'
  and i.title is distinct from mapped.new_title;

do $$
begin
  if exists (
    select 1 from rdl_title_backfill b
    join reading_materials m on m.material_id = b.material_id
    where m.title <> b.new_title
  ) then
    raise exception 'RDL material title verification failed';
  end if;
  if exists (
    select 1 from reading_logical_items i
    join reading_questions q on q.logical_item_id = i.logical_item_id
    join reading_materials m on m.material_id = q.material_id
    where i.module = 'rdl' and i.title <> m.title
  ) then
    raise exception 'RDL logical item/material title verification failed';
  end if;
end $$;

commit;
