-- Generated by tmp/generate-writing-assignment-title-backfill.mjs.
-- Run supabase/writing_assignment_group_titles.sql (Phase A) first.
-- supabase/writing_assignment_group_titles_cleanup.sql (Phase B) runs only
-- after the new code is committed, deployed and verified in production.
--
-- This file is a dry-run: the SELECT below prints the plan and the trailing
-- ROLLBACK guarantees that nothing changes. Review every row, then use the
-- commented apply block at the bottom if you want the safe rows updated.
--
-- Safe rows: 22 / 25. Only rows with can_auto_update = true
-- are ever touched; rows that may hold a teacher-edited title are kept as-is
-- (their cards keep today's display fallback until a manual decision is made).
-- base_auto_title and auto_title_sequence show the computed numbering; unsafe
-- and soft-deleted groups keep both null and never occupy a number.

begin;

create temporary table writing_assignment_group_title_plan (
  group_id uuid primary key,
  teacher_id uuid not null,
  old_title text,
  base_auto_title text,
  auto_title_sequence integer,
  proposed_new_title text,
  students text,
  assigned_date date,
  created_at timestamptz not null,
  email_count integer,
  ad_count integer,
  can_auto_update boolean not null,
  reason text
) on commit drop;

insert into writing_assignment_group_title_plan (
  group_id, teacher_id, old_title, base_auto_title, students, assigned_date,
  created_at, email_count, ad_count, can_auto_update, reason
) values
  ('02df5d72-2e19-4612-ad4c-9250224acab7', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目040 Training vs Low Prices', '陈俊伊 2026-09-18', '陈俊伊', '2026-09-18'::date, '2026-09-18T08:35:20.021Z'::timestamptz, 0, 1, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('2e9367ef-eda4-4999-8502-beb984962909', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目048 Technology Impact on Education 等 3 篇写作', '李梓瑜 2026-08-28', '李梓瑜', '2026-08-28'::date, '2026-08-28T08:40:27.634Z'::timestamptz, 0, 3, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('32fbecd0-a421-4a1b-a565-86f6fad0b39b', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目024 Academic and Work Balance', '陈俊伊 2026-09-18', '陈俊伊', '2026-09-18'::date, '2026-09-18T10:04:17.687Z'::timestamptz, 1, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('35363727-ca3d-4848-a70b-11204508fa2c', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目002 Personalization and Brand Loyalty', '陈俊伊 2026-09-18', '陈俊伊', '2026-09-18'::date, '2026-09-18T10:05:11.241Z'::timestamptz, 0, 1, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('38c1c92e-dc7b-4263-b48f-68c1d4776f0d', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目054 Renewable Energy vs Efficiency', '彭钰杰 2026-09-18', '彭钰杰', '2026-09-18'::date, '2026-09-18T10:13:11.059Z'::timestamptz, 0, 1, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('3cc85ba4-8c5f-4519-ba39-4bd439a9aef4', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目021 Hotel Stay Feedback', '彭钰杰 2026-09-18', '彭钰杰', '2026-09-18'::date, '2026-09-18T10:11:35.825Z'::timestamptz, 1, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('456e91b2-1e29-4c7f-9763-64e64c06c87f', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目059 Public Art and Identity', null, '蒋卓成', '2026-09-18'::date, '2026-09-18T08:04:23.907Z'::timestamptz, 0, 1, false, '全部题目已删除，无可见卡片'),
  ('479cf2cd-cf62-4214-8bcb-108337857d25', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目040 Training vs Low Prices 等 3 篇写作', '陈俊伊 2026-08-21', '陈俊伊', '2026-08-21'::date, '2026-08-21T06:00:36.527Z'::timestamptz, 0, 3, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('4acbaf65-3136-49ce-a1b5-69a479466577', '6f333422-384a-44fb-8a83-e9c1aadb0caf', 'E2E Admin Self 2026-08-27', null, 'admin', '2026-08-27'::date, '2026-08-27T03:53:19.260Z'::timestamptz, 1, 0, false, '自定义题目标题无法判定是否为教师手动修改，保留现状'),
  ('611de9a1-2e94-4e2b-a715-2ce5a328d802', 'bef319d4-3e57-4b78-aae2-95cac828b638', '260821-张宸皓 等 2 篇写作', '张宸皓 2026-08-21', '张宸皓', '2026-08-21'::date, '2026-08-21T02:57:02.545Z'::timestamptz, 2, 0, true, '自定义题目标题匹配旧版系统自动命名规则'),
  ('66402360-aed9-40eb-a48e-a20945eb55de', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目002 Fundraising Event Planning', '彭钰杰 2026-09-22', '彭钰杰', '2026-09-22'::date, '2026-09-22T07:52:21.741Z'::timestamptz, 1, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('6800a6be-ad82-4e8e-b32f-4c572f987e24', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '260829-张童予', '张童予 2026-08-29', '张童予', '2026-08-29'::date, '2026-08-29T08:22:28.473Z'::timestamptz, 1, 0, true, '自定义题目标题匹配旧版系统自动命名规则'),
  ('7345a079-18f0-453a-aeaa-53f742fe0cd0', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目048 Community Theater Costume Rentals', '蒋卓成 2026-09-18', '蒋卓成', '2026-09-18'::date, '2026-09-18T08:16:06.123Z'::timestamptz, 1, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('8f37a079-4071-4795-aa40-443ccd5f8cc5', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目039 Traditional vs Nontraditional Careers 等 4 篇写作', '李梓瑜 2026-09-17', '李梓瑜', '2026-09-17'::date, '2026-09-17T14:22:48.539Z'::timestamptz, 0, 4, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('913f7fc7-ca4d-4562-b901-90b0a44e845f', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目069 Summer Internship Documents', null, '蒋卓成', '2026-09-18'::date, '2026-09-18T08:03:47.196Z'::timestamptz, 1, 0, false, '全部题目已删除，无可见卡片'),
  ('97e18f23-7ebf-4a69-b48b-005137141b25', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目026 Project-Based Learning', '彭钰杰 2026-09-22', '彭钰杰', '2026-09-22'::date, '2026-09-22T07:51:25.683Z'::timestamptz, 0, 1, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('ac380b11-5c3d-4595-b767-291957475cc0', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目030 Dining Experience Feedback 等 2 篇写作', '冉阳 2026-09-19', '冉阳', '2026-09-19'::date, '2026-09-19T04:02:02.357Z'::timestamptz, 2, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('acf1121f-f060-4d07-8794-804ba944c0cc', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目030 Dining Experience Feedback 等 2 篇写作', '王思颖 2026-09-15', '王思颖', '2026-09-15'::date, '2026-09-15T14:05:49.520Z'::timestamptz, 2, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('c1d7f3ba-68cd-44f4-949f-011fcf3a9219', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目032 Eco-Friendly Resort Practices 等 2 篇写作', '张欣允 2026-08-23', '张欣允', '2026-08-23'::date, '2026-08-23T09:29:45.397Z'::timestamptz, 2, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('c225cbac-26a8-45de-aa1b-6d5201184745', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目026 Project-Based Learning 等 4 篇写作', '金韵雅 2026-09-16', '金韵雅', '2026-09-16'::date, '2026-09-16T08:14:59.191Z'::timestamptz, 0, 4, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('cad07437-6414-4e92-b1f7-fd266d913580', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目030 Dining Experience Feedback 等 4 篇写作', '金韵雅 2026-09-16', '金韵雅', '2026-09-16'::date, '2026-09-16T08:12:53.344Z'::timestamptz, 4, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('cfb12449-398f-45d8-8035-a50e408f6336', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目053 Preserving Indigenous Cultures 等 4 篇写作', '蔡沂熹 2026-08-25', '蔡沂熹', '2026-08-25'::date, '2026-08-25T09:14:15.504Z'::timestamptz, 0, 4, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('cfe469ad-963e-4947-98c5-68171f591a84', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目051 Individual vs Systemic Climate Action 等 2 篇写作', '陈乐阳 2026-09-15', '陈乐阳', '2026-09-15'::date, '2026-09-15T14:09:55.813Z'::timestamptz, 0, 2, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('eb1e73d5-7f9c-42bc-a5f8-256d40a34753', 'bef319d4-3e57-4b78-aae2-95cac828b638', '题目043 Workplace Emotional Intelligence 等 2 篇写作', '张宸皓 2026-08-21', '张宸皓', '2026-08-21'::date, '2026-08-21T03:56:13.848Z'::timestamptz, 0, 2, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
  ('f2a3eedc-ab9f-4b1c-a04d-efe27d248e3b', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目068 Environmental Solutions and Speed', '蒋卓成 2026-09-18', '蒋卓成', '2026-09-18'::date, '2026-09-18T08:16:52.959Z'::timestamptz, 0, 1, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成');

-- Numbering inside one teacher + one base title. The order is the real group
-- creation time with group_id as the stable tie-breaker, so re-running this
-- file always produces the same numbers. Unsafe and soft-deleted groups have
-- no base title and never occupy a number.
update writing_assignment_group_title_plan plan
set auto_title_sequence = numbered.sequence,
    proposed_new_title = case
      when numbered.sequence = 1 then plan.base_auto_title
      else plan.base_auto_title || ' (' || numbered.sequence || ')'
    end
from (
  select group_id,
         row_number() over (
           partition by teacher_id, base_auto_title
           order by created_at, group_id
         ) as sequence
  from writing_assignment_group_title_plan
  where can_auto_update
) numbered
where numbered.group_id = plan.group_id;

select
  plan.group_id,
  plan.old_title,
  plan.base_auto_title,
  plan.auto_title_sequence,
  plan.proposed_new_title,
  plan.students,
  plan.assigned_date,
  plan.email_count,
  plan.ad_count,
  plan.can_auto_update,
  plan.reason,
  groups.title as current_title
from writing_assignment_group_title_plan plan
join public.writing_assignment_groups groups using (group_id)
order by
  plan.assigned_date,
  plan.base_auto_title nulls last,
  plan.auto_title_sequence nulls last,
  plan.group_id;

rollback;

-- ---------------------------------------------------------------------------
-- Apply block (uncomment and run only after reviewing the dry-run above).
-- It recomputes the same plan and numbering, then updates safe rows whose
-- title is still null. Teacher-written titles are never overwritten.
-- ---------------------------------------------------------------------------
-- begin;
--
-- create temporary table writing_assignment_group_title_plan (
--   group_id uuid primary key,
--   teacher_id uuid not null,
--   old_title text,
--   base_auto_title text,
--   auto_title_sequence integer,
--   proposed_new_title text,
--   students text,
--   assigned_date date,
--   created_at timestamptz not null,
--   email_count integer,
--   ad_count integer,
--   can_auto_update boolean not null,
--   reason text
-- ) on commit drop;
--
-- insert into writing_assignment_group_title_plan (
--   group_id, teacher_id, old_title, base_auto_title, students, assigned_date,
--   created_at, email_count, ad_count, can_auto_update, reason
-- ) values
--   ('02df5d72-2e19-4612-ad4c-9250224acab7', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目040 Training vs Low Prices', '陈俊伊 2026-09-18', '陈俊伊', '2026-09-18'::date, '2026-09-18T08:35:20.021Z'::timestamptz, 0, 1, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('2e9367ef-eda4-4999-8502-beb984962909', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目048 Technology Impact on Education 等 3 篇写作', '李梓瑜 2026-08-28', '李梓瑜', '2026-08-28'::date, '2026-08-28T08:40:27.634Z'::timestamptz, 0, 3, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('32fbecd0-a421-4a1b-a565-86f6fad0b39b', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目024 Academic and Work Balance', '陈俊伊 2026-09-18', '陈俊伊', '2026-09-18'::date, '2026-09-18T10:04:17.687Z'::timestamptz, 1, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('35363727-ca3d-4848-a70b-11204508fa2c', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目002 Personalization and Brand Loyalty', '陈俊伊 2026-09-18', '陈俊伊', '2026-09-18'::date, '2026-09-18T10:05:11.241Z'::timestamptz, 0, 1, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('38c1c92e-dc7b-4263-b48f-68c1d4776f0d', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目054 Renewable Energy vs Efficiency', '彭钰杰 2026-09-18', '彭钰杰', '2026-09-18'::date, '2026-09-18T10:13:11.059Z'::timestamptz, 0, 1, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('3cc85ba4-8c5f-4519-ba39-4bd439a9aef4', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目021 Hotel Stay Feedback', '彭钰杰 2026-09-18', '彭钰杰', '2026-09-18'::date, '2026-09-18T10:11:35.825Z'::timestamptz, 1, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('456e91b2-1e29-4c7f-9763-64e64c06c87f', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目059 Public Art and Identity', null, '蒋卓成', '2026-09-18'::date, '2026-09-18T08:04:23.907Z'::timestamptz, 0, 1, false, '全部题目已删除，无可见卡片'),
--   ('479cf2cd-cf62-4214-8bcb-108337857d25', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目040 Training vs Low Prices 等 3 篇写作', '陈俊伊 2026-08-21', '陈俊伊', '2026-08-21'::date, '2026-08-21T06:00:36.527Z'::timestamptz, 0, 3, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('4acbaf65-3136-49ce-a1b5-69a479466577', '6f333422-384a-44fb-8a83-e9c1aadb0caf', 'E2E Admin Self 2026-08-27', null, 'admin', '2026-08-27'::date, '2026-08-27T03:53:19.260Z'::timestamptz, 1, 0, false, '自定义题目标题无法判定是否为教师手动修改，保留现状'),
--   ('611de9a1-2e94-4e2b-a715-2ce5a328d802', 'bef319d4-3e57-4b78-aae2-95cac828b638', '260821-张宸皓 等 2 篇写作', '张宸皓 2026-08-21', '张宸皓', '2026-08-21'::date, '2026-08-21T02:57:02.545Z'::timestamptz, 2, 0, true, '自定义题目标题匹配旧版系统自动命名规则'),
--   ('66402360-aed9-40eb-a48e-a20945eb55de', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目002 Fundraising Event Planning', '彭钰杰 2026-09-22', '彭钰杰', '2026-09-22'::date, '2026-09-22T07:52:21.741Z'::timestamptz, 1, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('6800a6be-ad82-4e8e-b32f-4c572f987e24', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '260829-张童予', '张童予 2026-08-29', '张童予', '2026-08-29'::date, '2026-08-29T08:22:28.473Z'::timestamptz, 1, 0, true, '自定义题目标题匹配旧版系统自动命名规则'),
--   ('7345a079-18f0-453a-aeaa-53f742fe0cd0', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目048 Community Theater Costume Rentals', '蒋卓成 2026-09-18', '蒋卓成', '2026-09-18'::date, '2026-09-18T08:16:06.123Z'::timestamptz, 1, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('8f37a079-4071-4795-aa40-443ccd5f8cc5', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目039 Traditional vs Nontraditional Careers 等 4 篇写作', '李梓瑜 2026-09-17', '李梓瑜', '2026-09-17'::date, '2026-09-17T14:22:48.539Z'::timestamptz, 0, 4, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('913f7fc7-ca4d-4562-b901-90b0a44e845f', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目069 Summer Internship Documents', null, '蒋卓成', '2026-09-18'::date, '2026-09-18T08:03:47.196Z'::timestamptz, 1, 0, false, '全部题目已删除，无可见卡片'),
--   ('97e18f23-7ebf-4a69-b48b-005137141b25', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目026 Project-Based Learning', '彭钰杰 2026-09-22', '彭钰杰', '2026-09-22'::date, '2026-09-22T07:51:25.683Z'::timestamptz, 0, 1, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('ac380b11-5c3d-4595-b767-291957475cc0', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目030 Dining Experience Feedback 等 2 篇写作', '冉阳 2026-09-19', '冉阳', '2026-09-19'::date, '2026-09-19T04:02:02.357Z'::timestamptz, 2, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('acf1121f-f060-4d07-8794-804ba944c0cc', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目030 Dining Experience Feedback 等 2 篇写作', '王思颖 2026-09-15', '王思颖', '2026-09-15'::date, '2026-09-15T14:05:49.520Z'::timestamptz, 2, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('c1d7f3ba-68cd-44f4-949f-011fcf3a9219', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目032 Eco-Friendly Resort Practices 等 2 篇写作', '张欣允 2026-08-23', '张欣允', '2026-08-23'::date, '2026-08-23T09:29:45.397Z'::timestamptz, 2, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('c225cbac-26a8-45de-aa1b-6d5201184745', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目026 Project-Based Learning 等 4 篇写作', '金韵雅 2026-09-16', '金韵雅', '2026-09-16'::date, '2026-09-16T08:14:59.191Z'::timestamptz, 0, 4, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('cad07437-6414-4e92-b1f7-fd266d913580', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目030 Dining Experience Feedback 等 4 篇写作', '金韵雅 2026-09-16', '金韵雅', '2026-09-16'::date, '2026-09-16T08:12:53.344Z'::timestamptz, 4, 0, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('cfb12449-398f-45d8-8035-a50e408f6336', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目053 Preserving Indigenous Cultures 等 4 篇写作', '蔡沂熹 2026-08-25', '蔡沂熹', '2026-08-25'::date, '2026-08-25T09:14:15.504Z'::timestamptz, 0, 4, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('cfe469ad-963e-4947-98c5-68171f591a84', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目051 Individual vs Systemic Climate Action 等 2 篇写作', '陈乐阳 2026-09-15', '陈乐阳', '2026-09-15'::date, '2026-09-15T14:09:55.813Z'::timestamptz, 0, 2, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('eb1e73d5-7f9c-42bc-a5f8-256d40a34753', 'bef319d4-3e57-4b78-aae2-95cac828b638', '题目043 Workplace Emotional Intelligence 等 2 篇写作', '张宸皓 2026-08-21', '张宸皓', '2026-08-21'::date, '2026-08-21T03:56:13.848Z'::timestamptz, 0, 2, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成'),
--   ('f2a3eedc-ab9f-4b1c-a04d-efe27d248e3b', 'bdd0bd35-e23d-4b59-934f-cbc9de875a93', '题目068 Environmental Solutions and Speed', '蒋卓成 2026-09-18', '蒋卓成', '2026-09-18'::date, '2026-09-18T08:16:52.959Z'::timestamptz, 0, 1, true, '题库题目从未有可编辑的作业标题，按收件人与布置日期生成');
--
-- -- Numbering inside one teacher + one base title. The order is the real group
-- -- creation time with group_id as the stable tie-breaker, so re-running this
-- -- file always produces the same numbers. Unsafe and soft-deleted groups have
-- -- no base title and never occupy a number.
-- update writing_assignment_group_title_plan plan
-- set auto_title_sequence = numbered.sequence,
--     proposed_new_title = case
--       when numbered.sequence = 1 then plan.base_auto_title
--       else plan.base_auto_title || ' (' || numbered.sequence || ')'
--     end
-- from (
--   select group_id,
--          row_number() over (
--            partition by teacher_id, base_auto_title
--            order by created_at, group_id
--          ) as sequence
--   from writing_assignment_group_title_plan
--   where can_auto_update
-- ) numbered
-- where numbered.group_id = plan.group_id;
--
-- -- Only safe rows are updated, and only while no title has been written yet.
-- update public.writing_assignment_groups groups
-- set title = plan.proposed_new_title
-- from writing_assignment_group_title_plan plan
-- where groups.group_id = plan.group_id
--   and plan.can_auto_update
--   and groups.title is null;
--
-- commit;
