import type { WritingTaskType } from "./writing.ts";
import { WRITING_REVIEW_C3_CONTENT_CATEGORIES, WRITING_REVIEW_C3_DIMENSIONS } from "./writingReviewSemanticSchema.ts";

export const WRITING_REVIEW_C3_PROMPT_VERSION = "writing_review_c3_prompt_v4" as const;
const anchors = `Anchor handling rules:\nThe markers such as ⟦TPS_UNIT:U01⟧ are TPS metadata, not student writing. Ignore them for scoring, grammar, organization, punctuation, formatting, and word count. Read anchored_response as one complete response; unit boundaries are not sentence boundaries. Use unit IDs only as location references. Never quote, revise, count, mention, or return a marker. revised_text contains only the revised student text for that unit.`;

export function buildWritingReviewSemanticC3Messages(input: { taskType: WritingTaskType; question: Record<string, unknown>; anchoredResponse: string }) {
  const dimensions = WRITING_REVIEW_C3_DIMENSIONS[input.taskType];
  const categories = WRITING_REVIEW_C3_CONTENT_CATEGORIES[input.taskType];
  const task = input.taskType === "email" ? "Evaluate completion of the email's communicative requirements, politeness, social conventions, greeting/closing, and specific content." : "Evaluate response to the professor, clear stance, genuine discussion participation, engagement with peers, elaboration, relevance, and coherence.";
  return [{ role: "system" as const, content: `You are an expert TOEFL writing rater. Use the official 0–5 rubric. ${anchors}\n${task}\nReturn one JSON object only: no prose before or after it and no Markdown code fence. Output all and only these dimension_scores keys: ${dimensions.join(", ")}. Every dimension has an integer 0–5 score and a short non-empty basis. If official_score is 0, every dimension score must be 0. If official_score is greater than 0, every dimension score must be from 1 through 5. Dimension scores may differ from official_score and from each other. Never average, add, weight, or reverse-engineer dimensions to produce official_score. Use dimension score 0 only when the whole response meets an official Score 0 condition. Content Feedback category must be exactly one of: ${categories.join(", ")}. Do not invent dimension names or categories. Each real unit ID may appear at most once in unit_revisions and at most once in content_feedback. If one unit has several issues, combine them into one issue, suggestion, and directly usable proposed_revision. Order content_feedback by importance; first is most important. Every Content Feedback must use a real unit ID and include proposed_revision. Put response-level advice in overall_feedback; never use null unit_id. Identify only meaningful language problems, preserve intended meaning, distinguish language revisions from content feedback, and never return offsets, exact original text, overlap decisions, database IDs, or a v2.2 object.` }, { role: "user" as const, content: JSON.stringify({ task_type: input.taskType, question: input.question, anchored_response: input.anchoredResponse }) }];
}
