import { lexicalSemanticProvenanceMatches } from "./provenance.ts";

export type SemanticCacheStage = "annotation" | "enrichment";

export type SemanticCacheQuarantineClassification = {
  group: "deepseek-flash" | "openrouter-gpt-oss-20b" | "unknown" | null;
  provider: string | null;
  model: string | null;
  reason: string | null;
};

export function classifySemanticCacheForQuarantine(
  stage: SemanticCacheStage,
  cache: Record<string, unknown>
): SemanticCacheQuarantineClassification {
  const model = typeof cache.model === "string" ? cache.model : null;
  const provider = typeof cache.provider === "string" ? cache.provider : null;
  if (lexicalSemanticProvenanceMatches(cache.provenance)) {
    return { group: null, provider, model, reason: null };
  }

  if (model === "deepseek-flash" || provider === "deepseek_flash") {
    return {
      group: "deepseek-flash",
      provider: provider ?? "deepseek_flash",
      model: model ?? "deepseek-flash",
      reason: "Semantic cache was generated by the prohibited DeepSeek provider."
    };
  }
  if (model === "openai/gpt-oss-20b" || provider === "openrouter") {
    return {
      group: "openrouter-gpt-oss-20b",
      provider: provider ?? "openrouter",
      model,
      reason: cache.recovered_by_lexeme === true
        ? "Semantic cache was generated through prohibited OpenRouter and unsafe corpus-global lexeme recovery."
        : "Semantic cache was generated by a prohibited OpenRouter provider."
    };
  }
  return {
    group: "unknown",
    provider,
    model,
    reason: `${stage} semantic cache has no trusted OpenChamber GPT-5.6 Sol provenance.`
  };
}
